# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9bff45cadb4459aae2d01c2dd2685d7e"
name = "EcomKit"
handle = "ecomkit-2"
application_url = "https://revelation-redeem-lying-latex.trycloudflare.com"
embedded = true
access_scopes = { }

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[auth]
redirect_urls = [
  "https://revelation-redeem-lying-latex.trycloudflare.com/auth/callback",
  "https://revelation-redeem-lying-latex.trycloudflare.com/auth/shopify/callback",
  "https://revelation-redeem-lying-latex.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[[extensions]]
type = "theme_app_extension"
name = "EcomKit Theme Extension"
