name = "BoostCartExtension"
uid = "f91861cb-b3d9-861b-1878-aa4ab4f49a9ed0b5f4f9"
type = "theme"

[settings]
path = "blocks/boost-cart.liquid"
extension_points = [
  # ... autres blocks ...
  { target = "section", path = "blocks/Bundle.liquid" }
]
